In [1]:
import numpy as np

In [4]:
#Create a five element array using your favorite numbers named myFavorites.
myFavorites = np.array([1, 5, 7, 9, 11])
print(myFavorites)

[ 1  5  7  9 11]


In [10]:
#Perform each of the five aggregate functions on your array.
myFavorites.max()

11

In [9]:
myFavorites.sum()

33

In [8]:
myFavorites.std()

3.4409301068170506

In [7]:
myFavorites.mean()

6.6

In [6]:
myFavorites.min()

1

In [11]:
#Create a five element array containing only ones named OneArrayToRuleThemAll.
OneArrayToRuleThemAll = np.ones(5)

In [12]:
#Add myFavorites and OneArrayToRuleThemAll.
OneArrayToRuleThemAll + myFavorites

array([ 2.,  6.,  8., 10., 12.])

In [13]:
#Multiply every element in myFavorites by two.
myFavorites * 2

array([ 2, 10, 14, 18, 22])

In [14]:
#Call the third element in myFavorites using indexing.
myFavorites[2]

7

In [41]:
#Create a four element, two-by-two matrix of numbers named TheMatrixHasYou.
TheMatrixHasYou = np.array([[5,2], [3,4]])
print(TheMatrixHasYou)

[[5 2]
 [3 4]]


In [42]:
#Access the upper left element in TheMatrixHasYou using indexing.
TheMatrixHasYou[0,0]

5

In [38]:
#Find the largest number in each row for TheMatrixHasYou.
TheMatrixHasYou.max(axis=0)
TheMatrixHasYou.max(axis=1)

array([5, 4])

In [39]:
#Reshape TheMatrixHasYou into a matrix with one row and four columns.
TheMatrixHasYou.reshape(1,4)

array([[5, 2, 3, 4]])